### ISSUE TITLE
A few manuscript questions/comments

### ISSUE THREAD

**Issue by sckott** [ropensci/RNeXML#116]
* https://github.com/ropensci/RNeXML/blame/master/manuscripts/manuscript.Rmd#L177 Do we want to suggest people go to discuss.ropensci.org as an additional option?
* https://github.com/ropensci/RNeXML/blame/master/manuscripts/manuscript.Rmd#L179-L180 Is there a reason these vignettes aren't in the CRAN version?  They're here in github, so i guess they will be in next cran version
* https://github.com/ropensci/RNeXML/blame/master/manuscripts/manuscript.Rmd#L600 s/"such as those"/"such those"

**Comment by cboettig** [comment]
Thanks for these!

- yup, vignettes should go up on CRAN in the next release (figured might as well wait for reviewer feedback since you know how touchy CRAN is)

- typo fixed.  

- didn't add the discuss.ropensci.org link since I think pointing just to issues is simpler (and I'm more likely to see it ;-) )

**Comment by sckott** [comment]
All sound good :)
