### ISSUE TITLE
Same namespace URI given under two different prefixes in default list of namespaces

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#154]
See: https://github.com/ropensci/RNeXML/pull/153#discussion_r68511277

Updated by @hlapp: `nexml_namespaces` defines the DC Terms URI both under prefixes `dcterms` (which is the one commonly used) and `ter` (which, to say the least, is not widely used).

**Comment by hlapp** [comment]
I would argue that with #219 we should be able to safely delete the redundant `ter` definition? (Although I'm using it in one of the tests.)

The only reason not to would be if we suspected that some clients or users out there are creating metas using this prefix for the property or relation, and never bothered to add the namespace because they figured it's predefined already. Possible, but not very likely?

**Comment by cboettig** [comment]
Right, I think it would be better to delete it.

**Comment by hlapp** [comment]
As part of the coming release?
