### ISSUE TITLE
Cut new release to CRAN?

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#228]
Looks like it's been time to re-release to CRAN after the changes following v2.2.0?

**Comment by cboettig** [comment]
Thanks, yup I think this is somewhat stuck in queue behind releasing the `taxadb` package we are now using in place of `taxize`, which isn't on CRAN yet (will want it to go through rOpenSci review first, which is quite thorough these days).  

Since it's a Suggested package only we could release it ahead of that, but would complicate installation for those features by requiring an additionalRepository

**Comment by cboettig** [comment]
Yeah, I agree, that's why the taxa lookup stuff is only a suggested dependency anyway.  This sounds good to me.  I'll try and get it onto CRAN by using the additional repositories mechanism.

**Comment by cboettig** [comment]
@hlapp I've pushed a new release to CRAN with the Additional_repositories mechanism.  🤞 we'll see what they say before I cut a new release on GitHub.

**Comment by cboettig** [comment]
On CRAN now
