### ISSUE TITLE
Thoughts on a hex?

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#230]
In the R community at least it's become [popular](http://hexb.in/) to icon-ify software in hexes.  I sketched out a simple concept using a public domain sketch of Darwin's first tree and XML's ubiquitous angle brackets here: https://github.com/ropensci/RNeXML/blob/master/man/figures/logo.svg.  Thoughts @rvosa @hlapp ?  (It's a simple SVG, feel free to hack away).

**Comment by hlapp** [comment]
Not bad 😄 The color wouldn't be my favorite one (but that's bound to be the case for someone no matter which color you choose). I guess my main feedback would be that the logo doesn't lend itself well to scaling down (making smaller) because then the thin lines of Darwin's sketch start to blur and fade into the background.

Note BTW that NeXML (the format) is one of the three [EvoIO foundation layers](https://github.com/evoinfo), which got its own logo many years ago.

(In theory there's the wiki evoio.org that has more of this. But I just discovered that somehow it must have gotten hosed, and the backups don't reach to before the time that must have happened. So it'll be a longer operation to try to recover that, but it could well be lost.)

**Comment by hlapp** [comment]
Are we settled on a hex now 😏

**Comment by hlapp** [comment]
Silence perhaps means agreement we're settled on one for now.
